// file1.js

const myArray = ["", "", "", "","","","","","","","","",""];
const myArray1 = ["0.02","8","70","932.697","739.65","70.151","83.615","534.79","182.819","55.465","486","2.5","30.6"]

const myObject = {
    1.4: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;अविनाशने 42 किमी 365 मीटर प्रवास बसने, 12 किमी 460 मी प्रवास मोटारने आणि 640 मीटर प्रवास पायी <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;केला, तर त्याने एकूण किती किमी प्रवास केला. (उत्तर दशांश अपूर्णांकांत लिहा.)</label><br><br><br><br><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num10' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br> <button class='button' id='tapasa3' style='position: absolute; top: 400; left: 550px; top:450px; width: 100px ; height: 35px ; font-size:25px'>नोंद करा</button>",
    1.5: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;आयेशाने सलवारसाठी 1.80 मीटर, कुर्त्यासाठी 2.25 मीटर कापड खरेदी केले. कापडाचा दर 120 रुपये प्रति <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; मीटर असेल, तर तिला दुकानदारास कापडासाठी किती रुपये द्यावे लागतील ?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num11' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br> <button class='button' id='tapasa4' style='position: absolute; top: 400; left: 550px;top:450px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    1.6: "	<label style ='position: absolute; text-align : left; font-size: 30px;'>सुजाताने बाजारातून 4.25 किग्रॅ वजनाचे कलिंगड आणले. त्यातील 1 किग्रॅ 750 ग्रॅम कलिंगड शेजारच्या मुलांना दिले, तर तिच्याकडे किती किलोग्रॅम कलिंगड शिल्लक राहिले?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num12' style='position: absolute;text-align: center; font-size: 30px;'><br>  <button class='button' id='tapasa5' style='position: absolute; top: 400; left: 571px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    1.7: "<label style ='position: absolute; text-align : left; font-size: 30px;'> अनिता कारने ताशी 85.6 किमी वेगाने प्रवास करत होती. रस्त्यावर ‘कारची वेगमर्यादा ताशी 55 किमी’ अशी सूचना होती. तर तिने गाडीचा वेग कितीने कमी केल्यास वाहतुकीच्या नियमांचे पालन होईल ?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num13' style='position: absolute;text-align: center; font-size: 30px;'><br>  <button class='button' id='tapasa6' style='position: absolute; top: 400; left: 571px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    3.1: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;जर, 317 × 45 = 14265, तर 3.17 × 4.5 = ?</label><br><br><br><br><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num7' style='position: absolute;text-align: center; font-size: 30px;'><br><br><br><br><br><br><br><p>बरोबर</p>",
    3.2: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;जर, 503 × 217 = 109151, तर 5.03 × 2.17 = ?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num1' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br><button class='button' id='tapasa1' style='position: absolute; top: 400; left: 550px;top:450px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    3.5: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;वेदिकाजवळ एकूण 23.50 मीटर कापड आहे. तिनेत्या कापडापासून समान आकाराचे 5 पडदे बनवले.<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; जर प्रत्येक पडद्यास 4 मीटर 25 सेमी कापड लागते, तर तिच्याजवळ किती मीटर कापड शिल्लक राहील ?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num11' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br> <button class='button' id='tapasa5' style='position: absolute; top: 400; left: 550px;top:450px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    4.2: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;रस्त्याची एकूण लांबी 4 किमी 800 मीटर आहे. रस्त्याच्या दुतर्फा दर 9.6 मीटर अंतरावर झाडेलावली,<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; तर एकूण कि ती झाडेलागतील ?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num1' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br> <button class='button' id='tapasa1' style='position: absolute; top: 400; left: 550px;top:450px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    4.3: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;प्रज्ञा दररोज नियमितपणे मैदानावरील वर्तुळाकार मार्गावरून चालण्याचा व्यायाम करते. जर ती दररोज<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9 फेऱ्यांत एकूण 3.825 किमी अंतर चालते, तर एका फ ेरीत ती किती अंतर चालते ?</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num4' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br><button class='button' id='tapasa2' style='position: absolute; top: 400; left: 550px;top:450px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",
    4.4: "<br><br><br><label style ='position: absolute; text-align : left; font-size: 30px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;औषधनिर्मात्याने0.25 क्विंटल हिरडा (औषधी वनस्पती) 9500 रुपयांना खरेदी केला, तर एक क्विंटल<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; हिरड्याचा दर किती ? (1क्विंटल = 100 किलोग्रॅम)</label><br><br><br><br><br><br><br><br><input type='number' step='0.01' id='num10' style='position: absolute;text-align: center; font-size: 30px; left: 400px; top:400px'><br> <button class='button' id='tapasa3' style='position: absolute; top: 400; left: 550px;top:450px; width: 100px ; height: 35px; font-size:25px'>नोंद करा</button>",

  };
  
  export default myObject;
  